server:
  port: 8989

spring:
  datasource: #数据源配置
    type: com.alibaba.druid.pool.DruidDataSource
    password: 123
    username: root
    driver-class-name: com.mysql.cj.jdbc.Driver  #数据库的程序驱动类
    url: jdbc:mysql://localhost:3306/mybatis?serverTimezone=GMT%2B8&characterEncoding=UTF-8
  resources:
    static-locations: classpath:/templates/ classpath:/static/ file:${photoDir}
  redis:
    host: localhost
    port: 6379
    database: 0
  profiles:
    active: dev #开发环境
mybatis:
  configuration:
    map-underscore-to-camel-case: true #数据库中的下划线自动转换成驼峰
  mapper-locations: classpath:/com/yujy/mapper/*.xml
  type-aliases-package: com.yujy.entity



photoDir:
  C:/Users/yujy/IdeaProjects/ems/src/main/resources/static/photo
